### ISSUE TITLE
TEST/Unit Test

### ISSUE THREAD

**Issue by shirley-kt** [SOEN6441-L/SOEN6441#83]
Must include tests for: 
(1) map validation – including map and continents being connected graphs; 
(2) reading an invalid map file; 
(3) validation of a correct startup phase; 
(4) calculation of number of reinforcement armies; 
(5) various test for the attack phase – including attacker/defender validation, valid move after conquering, and end of game;
(6) validation of a correct fortification phase. 

There must be a 1-to-1 relationship between implementation classes and test classes. 
Presence of a single test suite from which to run all test cases.

**Comment by shirley-kt** [comment]
Do not forget suite

**Comment by Lei-Xu** [comment]
All done
